[package]
name = "dsm"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"
description = "The boot time calibration logic for smart amp"

[dependencies]
audio_streams = "*"
cros_alsa = { path = "../../cros_alsa" } # provided by ebuild
libcras = { path = "../../cras/client/libcras" } # provided by ebuild
log = "0.4"
remain = "0.2.1"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8.11"
thiserror = "*"
