[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[dependencies]
audio_streams = "*" # provided by ebuild
clap = { version = "3.1.10", features = ["derive"] }
dbus = "0.9"
hound = "3.4.0"
libchromeos = { path = "../../../../../platform2/libchromeos-rs/" } # provided by ebuild
libcras = { version = "*", path = "../libcras" }
serde_json = "1.0.64"
thiserror = "1.0.20"

[build-dependencies]
chromeos-dbus-bindings = { path = "../../../../../platform2/chromeos-dbus-bindings" } # provided by ebuild
