[package]
name = "audio_processor"
version = "0.1.0"
edition = "2021"
authors = ["The ChromiumOS Authors"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Enable tests that only works with Bazel.
bazel = []

[dependencies]
assert_matches = "1.5.0"
clap = { version = "3.1.10", features = ["derive"] }
dasp_sample = "0.11.0"
hound = "3.4.0"
libc = "0.2.124"
thiserror = "1.0.30"

[build-dependencies]
bindgen = "0.63.0"
cc = "1.0.73"

[dev-dependencies]
tempfile = "3.4.0"
