[package]
name = "cras_rust"
version = "0.1.1"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.68"
libc = "0.2.44"
log = "0.4.17"
syslog = "6.0.1"
nix = "0.26.2"
glob = "0.3.0"
regex = "1.6.0"

cras_dlc = { version = "*", optional = true }
audio_processor = { version = "*", path = "../../audio_processor" }
