[package]
name = "libcras"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[lib]
path = "src/libcras.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.36"
audio_streams = "*"
cros_async = "*"
cras-sys = { version = "*", path = "../cras-sys" }
data_model = "*"
futures = "*"
libc = "*"
libchromeos = { path = "../../../../../platform2/libchromeos-rs/" } # provided by ebuild
serde = "1.0.125"
